/**
 * Hvigor Wrapper Script
 * This is a minimal wrapper that delegates to the actual hvigor module.
 * In a real project, this is auto-generated by DevEco Studio.
 */
const path = require('path');
const hvigorPath = path.join(__dirname, '..', 'node_modules', '@ohos', 'hvigor', 'bin', 'hvigor.js');
try {
  require(hvigorPath);
} catch (e) {
  console.error('Hvigor module not found. Please run: ohpm install');
  process.exit(1);
}
