#!/bin/sh

# ----------------------------------------------------------------------------
# Hvigor Startup Script for UN*X
# ----------------------------------------------------------------------------

# Determine the script directory
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done
PRGDIR=`dirname "$PRG"`

# Execute Hvigor
exec node "${PRGDIR}/hvigor/hvigor-wrapper.js" "$@"
